algorithm:
  name: reinforce
  rollout_length: 100
  gamma: 0.99

trainer:
  num_steps: 1000
  learning_rate: 0.001

  render_every_n_steps: 200
  save_every_n_steps: 200
  render_fps: 30

environment:
  name: CartPole-v1

seed: 42

logger:
  type: wandb
  mode: online  # online, offline, or disabled
