[project]
name = "backend"
version = "0.1.0"
description = "Backend for training the CartPole-v1 balancing bot policy"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium>=1.2.1",
    "ruff>=0.13.2",
    "torch>=2.8.0",
]
