version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "erenovic"
    assignees:
      - "erenovic"
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "@typescript-eslint/*"
          - "jest*"
          - "ts-jest"
          - "@biomejs/*"
      build-dependencies:
        patterns:
          - "vite*"
          - "typescript"
          - "rollup*"
          - "@rollup/*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "erenovic"
    assignees:
      - "erenovic"
